title: Optivem Open Source
tagline: Open Source
url: http://www.optivem.com

include: ['_pages']

permalink: /:year/:month/:day/:title

collections:
  pages:
    output: true
    permalink: /:path

sass:
  style: compressed
  
highlighter: rouge
